services:
  db:
    image: postgres:15-alpine
    container_name: sistema_contabil_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sistema_contabil_backend
    restart: always
    volumes:
      - ./backend:/app # Mapeia a pasta do backend para o container
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  frontend:
    image: node:20-alpine
    container_name: sistema_contabil_frontend
    restart: always
    working_dir: /app
    volumes:
      - ./frontend:/app # Mapeia a pasta do frontend para o container
      - /app/node_modules # Adiciona um volume anônimo para isolar node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  postgres_data: