"""Criação inicial de todas as tabelas

Revision ID: ff26e57d4ebd
Revises: 
Create Date: 2025-09-30 23:09:55.673994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff26e57d4ebd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('regime_tributario', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('papel', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('processamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('faturamento_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imposto_calculado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('data_processamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'mes', 'ano', name='_cliente_mes_ano_uc')
    )
    op.create_table('faturamento_detalhe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processamento_id', sa.Integer(), nullable=False),
    sa.Column('descricao_servico', sa.String(length=300), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['processamento_id'], ['processamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faturamento_detalhe')
    op.drop_table('processamento')
    op.drop_table('usuario')
    op.drop_table('cliente')
    # ### end Alembic commands ###
